# Generated by Django 6.0.6 on 2026-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_note',
            field=models.TextField(blank=True, default='', help_text='Explanation of the resolution or current progress.'),
        ),
    ]
